window.SITE_ITEMS = [
  {
    "id": "film-001",
    "title": "小偷家族",
    "originalTitle": "Shoplifters",
    "kind": "电影",
    "year": 2018,
    "score": "8.7",
    "genre": "家庭",
    "hot": 18020,
    "summary": "小偷家族是日本电影收录的日本电影内容，整理真实海报或剧照、年份评分、家庭题材、剧情介绍、导演演员资料和观影指南，适合查找日本电影推荐、经典日影与高清免费观影信息。",
    "poster": "./posters/film-001.jpg"
  },
  {
    "id": "film-002",
    "title": "电车狂",
    "originalTitle": "Dodesukaden",
    "kind": "电影",
    "year": 1970,
    "score": "8.2",
    "genre": "剧情",
    "hot": 17720,
    "summary": "电车狂是日本电影收录的日本电影内容，整理真实海报或剧照、年份评分、剧情题材、剧情介绍、导演演员资料和观影指南，适合查找日本电影推荐、经典日影与高清免费观影信息。",
    "poster": "./posters/film-002.jpg"
  },
  {
    "id": "film-003",
    "title": "影武者",
    "originalTitle": "Kagemusha",
    "kind": "电影",
    "year": 1980,
    "score": "8.9",
    "genre": "历史",
    "hot": 17680,
    "summary": "影武者是日本电影收录的日本电影内容，整理真实海报或剧照、年份评分、历史题材、剧情介绍、导演演员资料和观影指南，适合查找日本电影推荐、经典日影与高清免费观影信息。",
    "poster": "./posters/film-003.jpg"
  },
  {
    "id": "film-004",
    "title": "怪谈雪女郎",
    "originalTitle": "The Snow Woman",
    "kind": "电影",
    "year": 1968,
    "score": "7.8",
    "genre": "奇幻",
    "hot": 17430,
    "summary": "怪谈雪女郎是日本电影收录的日本电影内容，整理真实海报或剧照、年份评分、奇幻题材、剧情介绍、导演演员资料和观影指南，适合查找日本电影推荐、经典日影与高清免费观影信息。",
    "poster": "./posters/film-004.jpg"
  },
  {
    "id": "film-005",
    "title": "乱",
    "originalTitle": "Ran",
    "kind": "电影",
    "year": 1985,
    "score": "8.9",
    "genre": "历史",
    "hot": 17390,
    "summary": "乱是日本电影收录的日本电影内容，整理真实海报或剧照、年份评分、历史题材、剧情介绍、导演演员资料和观影指南，适合查找日本电影推荐、经典日影与高清免费观影信息。",
    "poster": "./posters/film-005.jpg"
  },
  {
    "id": "film-006",
    "title": "罗生门",
    "originalTitle": "Rashomon",
    "kind": "电影",
    "year": 1950,
    "score": "8.8",
    "genre": "悬疑",
    "hot": 17330,
    "summary": "罗生门是日本电影收录的日本电影内容，整理真实海报或剧照、年份评分、悬疑题材、剧情介绍、导演演员资料和观影指南，适合查找日本电影推荐、经典日影与高清免费观影信息。",
    "poster": "./posters/film-006.jpg"
  },
  {
    "id": "live-013",
    "title": "胜者即是正义",
    "originalTitle": "Legal High",
    "kind": "日剧",
    "year": 2012,
    "score": "9.1",
    "genre": "喜剧",
    "hot": 14597,
    "summary": "胜者即是正义是日本电影在线收录的日剧内容，整理真实海报或剧照、年份评分、喜剧题材、剧情介绍、导演演员资料和观影指南，适合查找日本电影推荐、日剧电影、日本动漫电影与经典日影信息。",
    "poster": "./posters/live-013.jpg"
  },
  {
    "id": "live-014",
    "title": "孤独的美食家",
    "originalTitle": "Solitary Gourmet",
    "kind": "日剧",
    "year": 2012,
    "score": "8.7",
    "genre": "美食",
    "hot": 14566,
    "summary": "孤独的美食家是日本电影在线收录的日剧内容，整理真实海报或剧照、年份评分、美食题材、剧情介绍、导演演员资料和观影指南，适合查找日本电影推荐、日剧电影、日本动漫电影与经典日影信息。",
    "poster": "./posters/live-014.jpg"
  },
  {
    "id": "live-015",
    "title": "深夜食堂",
    "originalTitle": "Midnight Diner",
    "kind": "日剧",
    "year": 2009,
    "score": "8.9",
    "genre": "生活",
    "hot": 14535,
    "summary": "深夜食堂是日本电影在线收录的日剧内容，整理真实海报或剧照、年份评分、生活题材、剧情介绍、导演演员资料和观影指南，适合查找日本电影推荐、日剧电影、日本动漫电影与经典日影信息。",
    "poster": "./posters/live-015.jpg"
  },
  {
    "id": "live-016",
    "title": "弥留之国的爱丽丝",
    "originalTitle": "Alice in Borderland",
    "kind": "日剧",
    "year": 2020,
    "score": "8.2",
    "genre": "悬疑",
    "hot": 14504,
    "summary": "弥留之国的爱丽丝是日本电影在线收录的日剧内容，整理真实海报或剧照、年份评分、悬疑题材、剧情介绍、导演演员资料和观影指南，适合查找日本电影推荐、日剧电影、日本动漫电影与经典日影信息。",
    "poster": "./posters/live-016.jpg"
  },
  {
    "id": "live-017",
    "title": "First Love 初恋",
    "originalTitle": "First Love",
    "kind": "日剧",
    "year": 2022,
    "score": "8.5",
    "genre": "爱情",
    "hot": 14473,
    "summary": "First Love 初恋是日本电影在线收录的日剧内容，整理真实海报或剧照、年份评分、爱情题材、剧情介绍、导演演员资料和观影指南，适合查找日本电影推荐、日剧电影、日本动漫电影与经典日影信息。",
    "poster": "./posters/live-017.jpg"
  },
  {
    "id": "live-018",
    "title": "忍者之家",
    "originalTitle": "House of Ninjas",
    "kind": "日剧",
    "year": 2024,
    "score": "7.8",
    "genre": "动作",
    "hot": 14442,
    "summary": "忍者之家是日本电影在线收录的日剧内容，整理真实海报或剧照、年份评分、动作题材、剧情介绍、导演演员资料和观影指南，适合查找日本电影推荐、日剧电影、日本动漫电影与经典日影信息。",
    "poster": "./posters/live-018.jpg"
  },
  {
    "id": "live-019",
    "title": "舞伎家的料理人",
    "originalTitle": "The Makanai",
    "kind": "日剧",
    "year": 2023,
    "score": "8.1",
    "genre": "生活",
    "hot": 14411,
    "summary": "舞伎家的料理人是日本电影在线收录的日剧内容，整理真实海报或剧照、年份评分、生活题材、剧情介绍、导演演员资料和观影指南，适合查找日本电影推荐、日剧电影、日本动漫电影与经典日影信息。",
    "poster": "./posters/live-019.jpg"
  },
  {
    "id": "live-020",
    "title": "火烧御手洗家",
    "originalTitle": "Burn the House Down",
    "kind": "日剧",
    "year": 2023,
    "score": "7.6",
    "genre": "悬疑",
    "hot": 14380,
    "summary": "火烧御手洗家是日本电影在线收录的日剧内容，整理真实海报或剧照、年份评分、悬疑题材、剧情介绍、导演演员资料和观影指南，适合查找日本电影推荐、日剧电影、日本动漫电影与经典日影信息。",
    "poster": "./posters/live-020.jpg"
  },
  {
    "id": "live-021",
    "title": "双层公寓",
    "originalTitle": "Terrace House",
    "kind": "综艺纪录",
    "year": 2015,
    "score": "8.0",
    "genre": "真人秀",
    "hot": 14349,
    "summary": "双层公寓是日本电影在线收录的综艺纪录内容，整理真实海报或剧照、年份评分、真人秀题材、剧情介绍、导演演员资料和观影指南，适合查找日本电影推荐、日剧电影、日本动漫电影与经典日影信息。",
    "poster": "./posters/live-021.jpg"
  },
  {
    "id": "drama-42847",
    "title": "Tokyo Vice",
    "originalTitle": "Tokyo Vice",
    "kind": "日剧",
    "year": 2022,
    "score": "7.6",
    "genre": "Drama",
    "hot": 9800,
    "summary": "Tokyo Vice收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-42847.jpg"
  },
  {
    "id": "drama-65571",
    "title": "Gannibal",
    "originalTitle": "Gannibal",
    "kind": "日剧",
    "year": 2022,
    "score": "5.9",
    "genre": "Horror",
    "hot": 8800,
    "summary": "Gannibal收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-65571.jpg"
  },
  {
    "id": "drama-154",
    "title": "Sanctuary",
    "originalTitle": "Sanctuary",
    "kind": "日剧",
    "year": 2008,
    "score": "8.0",
    "genre": "Drama",
    "hot": 9700,
    "summary": "Sanctuary收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-154.jpg"
  },
  {
    "id": "drama-46035",
    "title": "Followers",
    "originalTitle": "Followers",
    "kind": "日剧",
    "year": 2020,
    "score": "7.6",
    "genre": "Drama",
    "hot": 7200,
    "summary": "Followers收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-46035.jpg"
  },
  {
    "id": "drama-58982",
    "title": "History Erased",
    "originalTitle": "History Erased",
    "kind": "日剧",
    "year": 2019,
    "score": "7.6",
    "genre": "剧情",
    "hot": 2900,
    "summary": "History Erased收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-58982.jpg"
  },
  {
    "id": "drama-19444",
    "title": "Good Morning Call",
    "originalTitle": "Good Morning Call",
    "kind": "日剧",
    "year": 2016,
    "score": "7.8",
    "genre": "Drama",
    "hot": 8800,
    "summary": "Good Morning Call收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-19444.jpg"
  },
  {
    "id": "drama-10706",
    "title": "Atelier",
    "originalTitle": "Atelier",
    "kind": "日剧",
    "year": 2015,
    "score": "7.6",
    "genre": "Drama",
    "hot": 6900,
    "summary": "Atelier收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-10706.jpg"
  },
  {
    "id": "drama-37881",
    "title": "Switched",
    "originalTitle": "Switched",
    "kind": "日剧",
    "year": 2018,
    "score": "7.6",
    "genre": "Drama",
    "hot": 4400,
    "summary": "Switched收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-37881.jpg"
  },
  {
    "id": "drama-42224",
    "title": "The Naked Director",
    "originalTitle": "The Naked Director",
    "kind": "日剧",
    "year": 2019,
    "score": "6.1",
    "genre": "Drama",
    "hot": 7800,
    "summary": "The Naked Director收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-42224.jpg"
  },
  {
    "id": "drama-69124",
    "title": "Watashi no Shiawase na Kekkon",
    "originalTitle": "Watashi no Shiawase na Kekkon",
    "kind": "日剧",
    "year": 2023,
    "score": "6.4",
    "genre": "Anime",
    "hot": 8400,
    "summary": "Watashi no Shiawase na Kekkon收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-69124.jpg"
  },
  {
    "id": "drama-79147",
    "title": "Trillion Game",
    "originalTitle": "Trillion Game",
    "kind": "日剧",
    "year": 2024,
    "score": "6.8",
    "genre": "Anime",
    "hot": 8200,
    "summary": "Trillion Game收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-79147.jpg"
  },
  {
    "id": "drama-73519",
    "title": "Vivant",
    "originalTitle": "Vivant",
    "kind": "日剧",
    "year": 2023,
    "score": "7.6",
    "genre": "剧情",
    "hot": 2900,
    "summary": "Vivant收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-73519.jpg"
  },
  {
    "id": "drama-67489",
    "title": "Brush Up Life",
    "originalTitle": "Brush Up Life",
    "kind": "日剧",
    "year": 2023,
    "score": "7.6",
    "genre": "Drama",
    "hot": 4000,
    "summary": "Brush Up Life收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-67489.jpg"
  },
  {
    "id": "drama-18858",
    "title": "Doctor-X",
    "originalTitle": "Doctor-X",
    "kind": "日剧",
    "year": 2012,
    "score": "7.6",
    "genre": "Drama",
    "hot": 4000,
    "summary": "Doctor-X收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-18858.jpg"
  },
  {
    "id": "drama-35148",
    "title": "Unnatural",
    "originalTitle": "Unnatural",
    "kind": "日剧",
    "year": 2018,
    "score": "7.6",
    "genre": "Drama",
    "hot": 5600,
    "summary": "Unnatural收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-35148.jpg"
  },
  {
    "id": "drama-11740",
    "title": "Hana Yori Dango",
    "originalTitle": "Hana Yori Dango",
    "kind": "日剧",
    "year": 1996,
    "score": "7.6",
    "genre": "Comedy",
    "hot": 6600,
    "summary": "Hana Yori Dango收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-11740.jpg"
  },
  {
    "id": "drama-6940",
    "title": "Nodame Cantabile",
    "originalTitle": "Nodame Cantabile",
    "kind": "日剧",
    "year": 2007,
    "score": "7.6",
    "genre": "Drama",
    "hot": 4800,
    "summary": "Nodame Cantabile收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-6940.jpg"
  },
  {
    "id": "drama-78451",
    "title": "The Queen of Villains",
    "originalTitle": "The Queen of Villains",
    "kind": "日剧",
    "year": 2024,
    "score": "5.5",
    "genre": "Drama",
    "hot": 4400,
    "summary": "The Queen of Villains收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-78451.jpg"
  },
  {
    "id": "drama-69918",
    "title": "Turn to me Mukai-kun",
    "originalTitle": "Turn to me Mukai-kun",
    "kind": "日剧",
    "year": 2023,
    "score": "7.6",
    "genre": "剧情",
    "hot": 1000,
    "summary": "Turn to me Mukai-kun收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-69918.jpg"
  },
  {
    "id": "drama-37336",
    "title": "Shōgun",
    "originalTitle": "Shōgun",
    "kind": "日剧",
    "year": 2024,
    "score": "8.5",
    "genre": "Drama",
    "hot": 10000,
    "summary": "Shōgun收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-37336.jpg"
  },
  {
    "id": "drama-68683",
    "title": "Burn the House Down",
    "originalTitle": "Burn the House Down",
    "kind": "日剧",
    "year": 2023,
    "score": "6.8",
    "genre": "Drama",
    "hot": 7200,
    "summary": "Burn the House Down收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-68683.jpg"
  },
  {
    "id": "drama-64015",
    "title": "House of Ninjas",
    "originalTitle": "House of Ninjas",
    "kind": "日剧",
    "year": 2024,
    "score": "7.0",
    "genre": "Drama",
    "hot": 9500,
    "summary": "House of Ninjas收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-64015.jpg"
  },
  {
    "id": "drama-84230",
    "title": "First Love",
    "originalTitle": "First Love",
    "kind": "日剧",
    "year": 2025,
    "score": "7.6",
    "genre": "Drama",
    "hot": 7500,
    "summary": "First Love收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-84230.jpg"
  },
  {
    "id": "drama-37376",
    "title": "Midnight Diner",
    "originalTitle": "Midnight Diner",
    "kind": "日剧",
    "year": 2009,
    "score": "7.6",
    "genre": "Drama",
    "hot": 4300,
    "summary": "Midnight Diner收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-37376.jpg"
  },
  {
    "id": "drama-50036",
    "title": "Alice in Borderland",
    "originalTitle": "Alice in Borderland",
    "kind": "日剧",
    "year": 2020,
    "score": "7.8",
    "genre": "Science-Fiction",
    "hot": 9900,
    "summary": "Alice in Borderland收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-50036.jpg"
  },
  {
    "id": "drama-59841",
    "title": "The Makanai: Cooking for the Maiko House",
    "originalTitle": "The Makanai: Cooking for the Maiko House",
    "kind": "日剧",
    "year": 2023,
    "score": "7.6",
    "genre": "Drama",
    "hot": 4500,
    "summary": "The Makanai: Cooking for the Maiko House收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-59841.jpg"
  },
  {
    "id": "drama-27063",
    "title": "Kodoku no Gurume",
    "originalTitle": "Kodoku no Gurume",
    "kind": "日剧",
    "year": 2012,
    "score": "7.6",
    "genre": "Drama",
    "hot": 8100,
    "summary": "Kodoku no Gurume收录真实剧集海报或剧照、评分、年份、题材和剧情介绍，适合日剧电影、日本影视资源和高清观影指南页面展示。",
    "poster": "./posters/drama-27063.jpg"
  },
  {
    "id": "anime-57555",
    "title": "Chainsaw Man – The Movie: Reze Arc",
    "originalTitle": "劇場版 チェンソーマン レゼ篇",
    "kind": "动漫电影",
    "year": 2025,
    "score": "9.1",
    "genre": "Action",
    "hot": 511687,
    "summary": "Chainsaw Man – The Movie: Reze Arc收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-57555.jpg"
  },
  {
    "id": "anime-39486",
    "title": "Gintama: The Very Final",
    "originalTitle": "銀魂 THE FINAL",
    "kind": "动漫电影",
    "year": 2021,
    "score": "9.1",
    "genre": "Action",
    "hot": 186169,
    "summary": "Gintama: The Very Final收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-39486.jpg"
  },
  {
    "id": "anime-28851",
    "title": "A Silent Voice",
    "originalTitle": "聲の形",
    "kind": "动漫电影",
    "year": 2016,
    "score": "8.9",
    "genre": "Award Winning",
    "hot": 2636970,
    "summary": "A Silent Voice收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-28851.jpg"
  },
  {
    "id": "anime-15335",
    "title": "Gintama: The Movie: The Final Chapter: Be Forever Yorozuya",
    "originalTitle": "劇場版 銀魂 完結篇 万事屋よ永遠なれ",
    "kind": "动漫电影",
    "year": 2013,
    "score": "8.9",
    "genre": "Action",
    "hot": 263757,
    "summary": "Gintama: The Movie: The Final Chapter: Be Forever Yorozuya收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-15335.jpg"
  },
  {
    "id": "anime-59571",
    "title": "Attack on Titan: The Last Attack",
    "originalTitle": "劇場版 進撃の巨人 完結編 THE LAST ATTACK",
    "kind": "动漫电影",
    "year": 2024,
    "score": "8.8",
    "genre": "Action",
    "hot": 94285,
    "summary": "Attack on Titan: The Last Attack收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-59571.jpg"
  },
  {
    "id": "anime-37987",
    "title": "Violet Evergarden: The Movie",
    "originalTitle": "劇場版 ヴァイオレット・エヴァーガーデン",
    "kind": "动漫电影",
    "year": 2020,
    "score": "8.8",
    "genre": "Award Winning",
    "hot": 736586,
    "summary": "Violet Evergarden: The Movie收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-37987.jpg"
  },
  {
    "id": "anime-32281",
    "title": "Your Name.",
    "originalTitle": "君の名は。",
    "kind": "动漫电影",
    "year": 2016,
    "score": "8.8",
    "genre": "Award Winning",
    "hot": 3046371,
    "summary": "Your Name.收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-32281.jpg"
  },
  {
    "id": "anime-31758",
    "title": "Kizumonogatari Part 3: Cold-Blooded",
    "originalTitle": "傷物語〈Ⅲ冷血篇〉",
    "kind": "动漫电影",
    "year": 2017,
    "score": "8.8",
    "genre": "Action",
    "hot": 516682,
    "summary": "Kizumonogatari Part 3: Cold-Blooded收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-31758.jpg"
  },
  {
    "id": "anime-199",
    "title": "Spirited Away",
    "originalTitle": "千と千尋の神隠し",
    "kind": "动漫电影",
    "year": 2001,
    "score": "8.8",
    "genre": "Adventure",
    "hot": 2039965,
    "summary": "Spirited Away收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-199.jpg"
  },
  {
    "id": "anime-52198",
    "title": "Kaguya-sama: Love is War -The First Kiss That Never Ends-",
    "originalTitle": "かぐや様は告らせたい -ファーストキッスは終わらない-",
    "kind": "动漫电影",
    "year": 2022,
    "score": "8.7",
    "genre": "Comedy",
    "hot": 388992,
    "summary": "Kaguya-sama: Love is War -The First Kiss That Never Ends-收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-52198.jpg"
  },
  {
    "id": "anime-45649",
    "title": "The First Slam Dunk",
    "originalTitle": "THE FIRST SLAM DUNK",
    "kind": "动漫电影",
    "year": 2022,
    "score": "8.7",
    "genre": "Award Winning",
    "hot": 78591,
    "summary": "The First Slam Dunk收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-45649.jpg"
  },
  {
    "id": "anime-431",
    "title": "Howl's Moving Castle",
    "originalTitle": "ハウルの動く城",
    "kind": "动漫电影",
    "year": 2004,
    "score": "8.7",
    "genre": "Adventure",
    "hot": 1500307,
    "summary": "Howl's Moving Castle收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-431.jpg"
  },
  {
    "id": "anime-164",
    "title": "Princess Mononoke",
    "originalTitle": "もののけ姫",
    "kind": "动漫电影",
    "year": 1997,
    "score": "8.7",
    "genre": "Action",
    "hot": 1389154,
    "summary": "Princess Mononoke收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-164.jpg"
  },
  {
    "id": "anime-59192",
    "title": "Demon Slayer: Kimetsu no Yaiba - The Movie: Infinity Castle - Part 1: Akaza Returns",
    "originalTitle": "劇場版 鬼滅の刃 無限城編 第一章 猗窩座再来",
    "kind": "动漫电影",
    "year": 2025,
    "score": "8.7",
    "genre": "Action",
    "hot": 392459,
    "summary": "Demon Slayer: Kimetsu no Yaiba - The Movie: Infinity Castle - Part 1: Akaza Returns收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-59192.jpg"
  },
  {
    "id": "anime-57647",
    "title": "Umamusume: Pretty Derby - Beginning of a New Era",
    "originalTitle": "ウマ娘 プリティーダービー 新時代の扉",
    "kind": "动漫电影",
    "year": 2024,
    "score": "8.6",
    "genre": "Sports",
    "hot": 61967,
    "summary": "Umamusume: Pretty Derby - Beginning of a New Era收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-57647.jpg"
  },
  {
    "id": "anime-33050",
    "title": "Fate/stay night: Heaven's Feel - III. Spring Song",
    "originalTitle": "劇場版「Fate/stay night [Heaven's Feel] III.spring song」",
    "kind": "动漫电影",
    "year": 2020,
    "score": "8.6",
    "genre": "Action",
    "hot": 411931,
    "summary": "Fate/stay night: Heaven's Feel - III. Spring Song收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-33050.jpg"
  },
  {
    "id": "anime-52742",
    "title": "Haikyu!! Movie: The Dumpster Battle",
    "originalTitle": "劇場版ハイキュー!! ゴミ捨て場の決戦",
    "kind": "动漫电影",
    "year": 2024,
    "score": "8.6",
    "genre": "Sports",
    "hot": 234000,
    "summary": "Haikyu!! Movie: The Dumpster Battle收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-52742.jpg"
  },
  {
    "id": "anime-58125",
    "title": "Look Back",
    "originalTitle": "ルックバック",
    "kind": "动漫电影",
    "year": 2024,
    "score": "8.6",
    "genre": "Award Winning",
    "hot": 253304,
    "summary": "Look Back收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-58125.jpg"
  },
  {
    "id": "anime-4565",
    "title": "Gurren Lagann The Movie: The Lights in the Sky are Stars",
    "originalTitle": "劇場版 天元突破グレンラガン 螺巌篇",
    "kind": "动漫电影",
    "year": 2009,
    "score": "8.6",
    "genre": "Sci-Fi",
    "hot": 240370,
    "summary": "Gurren Lagann The Movie: The Lights in the Sky are Stars收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-4565.jpg"
  },
  {
    "id": "anime-36862",
    "title": "Made in Abyss: Dawn of the Deep Soul",
    "originalTitle": "劇場版メイドインアビス 深き魂の黎明",
    "kind": "动漫电影",
    "year": 2020,
    "score": "8.6",
    "genre": "Adventure",
    "hot": 542389,
    "summary": "Made in Abyss: Dawn of the Deep Soul收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-36862.jpg"
  },
  {
    "id": "anime-38329",
    "title": "Rascal Does Not Dream of a Dreaming Girl",
    "originalTitle": "青春ブタ野郎はゆめみる少女の夢を見ない",
    "kind": "动漫电影",
    "year": 2019,
    "score": "8.6",
    "genre": "Drama",
    "hot": 829446,
    "summary": "Rascal Does Not Dream of a Dreaming Girl收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-38329.jpg"
  },
  {
    "id": "anime-7311",
    "title": "The Disappearance of Haruhi Suzumiya",
    "originalTitle": "涼宮ハルヒの消失",
    "kind": "动漫电影",
    "year": 2010,
    "score": "8.6",
    "genre": "Award Winning",
    "hot": 652690,
    "summary": "The Disappearance of Haruhi Suzumiya收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-7311.jpg"
  },
  {
    "id": "anime-3786",
    "title": "Evangelion: 3.0+1.0 Thrice Upon a Time",
    "originalTitle": "シン・エヴァンゲリオン劇場版𝄇",
    "kind": "动漫电影",
    "year": 2021,
    "score": "8.6",
    "genre": "Award Winning",
    "hot": 428120,
    "summary": "Evangelion: 3.0+1.0 Thrice Upon a Time收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-3786.jpg"
  },
  {
    "id": "anime-28957",
    "title": "Mushi-Shi: The Next Chapter - Drops of Bells",
    "originalTitle": "蟲師 続章: 鈴の雫",
    "kind": "动漫电影",
    "year": 2015,
    "score": "8.6",
    "genre": "Adventure",
    "hot": 141691,
    "summary": "Mushi-Shi: The Next Chapter - Drops of Bells收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-28957.jpg"
  },
  {
    "id": "anime-32",
    "title": "Neon Genesis Evangelion: The End of Evangelion",
    "originalTitle": "新世紀エヴァンゲリオン劇場版 Air / まごころを, 君に",
    "kind": "动漫电影",
    "year": 1997,
    "score": "8.6",
    "genre": "Avant Garde",
    "hot": 1050886,
    "summary": "Neon Genesis Evangelion: The End of Evangelion收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-32.jpg"
  },
  {
    "id": "anime-31757",
    "title": "Kizumonogatari Part 2: Hot-Blooded",
    "originalTitle": "傷物語〈Ⅱ熱血篇〉",
    "kind": "动漫电影",
    "year": 2016,
    "score": "8.6",
    "genre": "Action",
    "hot": 492167,
    "summary": "Kizumonogatari Part 2: Hot-Blooded收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-31757.jpg"
  },
  {
    "id": "anime-12355",
    "title": "Wolf Children",
    "originalTitle": "おおかみこどもの雨と雪",
    "kind": "动漫电影",
    "year": 2012,
    "score": "8.6",
    "genre": "Award Winning",
    "hot": 871819,
    "summary": "Wolf Children收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-12355.jpg"
  },
  {
    "id": "anime-437",
    "title": "Perfect Blue",
    "originalTitle": "パーフェクトブルー",
    "kind": "动漫电影",
    "year": 1998,
    "score": "8.6",
    "genre": "Avant Garde",
    "hot": 830255,
    "summary": "Perfect Blue收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-437.jpg"
  },
  {
    "id": "anime-36098",
    "title": "I Want To Eat Your Pancreas",
    "originalTitle": "君の膵臓をたべたい",
    "kind": "动漫电影",
    "year": 2018,
    "score": "8.6",
    "genre": "Drama",
    "hot": 1129733,
    "summary": "I Want To Eat Your Pancreas收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-36098.jpg"
  },
  {
    "id": "anime-578",
    "title": "Grave of the Fireflies",
    "originalTitle": "火垂るの墓",
    "kind": "动漫电影",
    "year": 1988,
    "score": "8.5",
    "genre": "Drama",
    "hot": 773566,
    "summary": "Grave of the Fireflies收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-578.jpg"
  },
  {
    "id": "anime-40456",
    "title": "Demon Slayer: Kimetsu no Yaiba - The Movie: Mugen Train",
    "originalTitle": "劇場版 鬼滅の刃 無限列車編",
    "kind": "动漫电影",
    "year": 2020,
    "score": "8.5",
    "genre": "Action",
    "hot": 1792294,
    "summary": "Demon Slayer: Kimetsu no Yaiba - The Movie: Mugen Train收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-40456.jpg"
  },
  {
    "id": "anime-7472",
    "title": "Gintama: The Movie",
    "originalTitle": "劇場版 銀魂 新訳紅桜篇",
    "kind": "动漫电影",
    "year": 2010,
    "score": "8.5",
    "genre": "Action",
    "hot": 178305,
    "summary": "Gintama: The Movie收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-7472.jpg"
  },
  {
    "id": "anime-40664",
    "title": "Revue Starlight: The Movie",
    "originalTitle": "劇場版 少女☆歌劇 レヴュースタァライト",
    "kind": "动漫电影",
    "year": 2021,
    "score": "8.5",
    "genre": "Drama",
    "hot": 26398,
    "summary": "Revue Starlight: The Movie收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-40664.jpg"
  },
  {
    "id": "anime-11981",
    "title": "Puella Magi Madoka Magica the Movie: Rebellion",
    "originalTitle": "劇場版 魔法少女まどか☆マギカ 叛逆の物語",
    "kind": "动漫电影",
    "year": 2013,
    "score": "8.5",
    "genre": "Award Winning",
    "hot": 424705,
    "summary": "Puella Magi Madoka Magica the Movie: Rebellion收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-11981.jpg"
  },
  {
    "id": "anime-58222",
    "title": "given The Movie: To the Sea",
    "originalTitle": "映画 ギヴン 海へ",
    "kind": "动漫电影",
    "year": 2024,
    "score": "8.5",
    "genre": "Boys Love",
    "hot": 32986,
    "summary": "given The Movie: To the Sea收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-58222.jpg"
  },
  {
    "id": "anime-4282",
    "title": "The Garden of Sinners Chapter 5: Paradox Spiral",
    "originalTitle": "劇場版 空の境界 the Garden of sinners 第五章『矛盾螺旋』",
    "kind": "动漫电影",
    "year": 2008,
    "score": "8.5",
    "genre": "Action",
    "hot": 254882,
    "summary": "The Garden of Sinners Chapter 5: Paradox Spiral收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-4282.jpg"
  },
  {
    "id": "anime-33049",
    "title": "Fate/stay night: Heaven's Feel - II. Lost Butterfly",
    "originalTitle": "劇場版「Fate/stay night [Heaven's Feel] II.lost butterfly」",
    "kind": "动漫电影",
    "year": 2019,
    "score": "8.5",
    "genre": "Action",
    "hot": 442445,
    "summary": "Fate/stay night: Heaven's Feel - II. Lost Butterfly收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-33049.jpg"
  },
  {
    "id": "anime-11577",
    "title": "Steins;Gate: The Movie - Load Region of Déjà Vu",
    "originalTitle": "劇場版 シュタインズゲート 負荷領域のデジャヴ",
    "kind": "动漫电影",
    "year": 2013,
    "score": "8.4",
    "genre": "Drama",
    "hot": 646819,
    "summary": "Steins;Gate: The Movie - Load Region of Déjà Vu收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-11577.jpg"
  },
  {
    "id": "anime-39741",
    "title": "Violet Evergarden: Eternity and the Auto Memory Doll",
    "originalTitle": "ヴァイオレット・エヴァーガーデン 外伝 -永遠と自動手記人形-",
    "kind": "动漫电影",
    "year": 2019,
    "score": "8.4",
    "genre": "Drama",
    "hot": 486936,
    "summary": "Violet Evergarden: Eternity and the Auto Memory Doll收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-39741.jpg"
  },
  {
    "id": "anime-36538",
    "title": "Natsume's Book of Friends Movie: Ephemeral Bond",
    "originalTitle": "劇場版 夏目友人帳 ～うつせみに結ぶ～",
    "kind": "动漫电影",
    "year": 2018,
    "score": "8.4",
    "genre": "Slice of Life",
    "hot": 84629,
    "summary": "Natsume's Book of Friends Movie: Ephemeral Bond收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-36538.jpg"
  },
  {
    "id": "anime-36885",
    "title": "Saekano the Movie: Finale",
    "originalTitle": "冴えない彼女の育てかた Fine",
    "kind": "动漫电影",
    "year": 2019,
    "score": "8.4",
    "genre": "Comedy",
    "hot": 206351,
    "summary": "Saekano the Movie: Finale收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-36885.jpg"
  },
  {
    "id": "anime-21899",
    "title": "Gintama: Yorinuki Gintama-san on Theater 2D",
    "originalTitle": "銀魂 よりぬき銀魂さんオンシアター2D",
    "kind": "动漫电影",
    "year": 2012,
    "score": "8.4",
    "genre": "Action",
    "hot": 48981,
    "summary": "Gintama: Yorinuki Gintama-san on Theater 2D收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-21899.jpg"
  },
  {
    "id": "anime-35851",
    "title": "Maquia: When the Promised Flower Blooms",
    "originalTitle": "さよならの朝に約束の花をかざろう",
    "kind": "动漫电影",
    "year": 2018,
    "score": "8.4",
    "genre": "Drama",
    "hot": 499197,
    "summary": "Maquia: When the Promised Flower Blooms收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-35851.jpg"
  },
  {
    "id": "anime-49722",
    "title": "Teasing Master Takagi-san: The Movie",
    "originalTitle": "からかい上手の高木さん",
    "kind": "动漫电影",
    "year": 2022,
    "score": "8.4",
    "genre": "Romance",
    "hot": 97155,
    "summary": "Teasing Master Takagi-san: The Movie收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-49722.jpg"
  },
  {
    "id": "anime-50183",
    "title": "Blue Giant",
    "originalTitle": "BLUE GIANT",
    "kind": "动漫电影",
    "year": 2023,
    "score": "8.4",
    "genre": "Drama",
    "hot": 50000,
    "summary": "Blue Giant收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-50183.jpg"
  },
  {
    "id": "anime-38040",
    "title": "KonoSuba: God's Blessing on This Wonderful World! - Legend of Crimson",
    "originalTitle": "映画 この素晴らしい世界に祝福を！紅伝説",
    "kind": "动漫电影",
    "year": 2019,
    "score": "8.4",
    "genre": "Adventure",
    "hot": 894136,
    "summary": "KonoSuba: God's Blessing on This Wonderful World! - Legend of Crimson收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-38040.jpg"
  },
  {
    "id": "anime-37515",
    "title": "Made in Abyss: Wandering Twilight",
    "originalTitle": "劇場版総集編【後編】メイドインアビス 放浪する黄昏",
    "kind": "动漫电影",
    "year": 2019,
    "score": "8.4",
    "genre": "Adventure",
    "hot": 166889,
    "summary": "Made in Abyss: Wandering Twilight收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-37515.jpg"
  },
  {
    "id": "anime-39167",
    "title": "Girls und Panzer das Finale – Part 4",
    "originalTitle": "『ガールズ＆パンツァー 最終章』第4話",
    "kind": "动漫电影",
    "year": 2023,
    "score": "8.4",
    "genre": "动画",
    "hot": 27833,
    "summary": "Girls und Panzer das Finale – Part 4收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-39167.jpg"
  },
  {
    "id": "anime-11979",
    "title": "Puella Magi Madoka Magica the Movie Part 2: Eternal",
    "originalTitle": "劇場版 魔法少女まどか☆マギカ 永遠の物語",
    "kind": "动漫电影",
    "year": 2012,
    "score": "8.4",
    "genre": "Drama",
    "hot": 221799,
    "summary": "Puella Magi Madoka Magica the Movie Part 2: Eternal收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-11979.jpg"
  },
  {
    "id": "anime-40787",
    "title": "Josee, the Tiger and the Fish",
    "originalTitle": "ジョゼと虎と魚たち",
    "kind": "动漫电影",
    "year": 2020,
    "score": "8.4",
    "genre": "Drama",
    "hot": 538686,
    "summary": "Josee, the Tiger and the Fish收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-40787.jpg"
  },
  {
    "id": "anime-5",
    "title": "Cowboy Bebop: The Movie",
    "originalTitle": "カウボーイビバップ 天国の扉",
    "kind": "动漫电影",
    "year": 2001,
    "score": "8.4",
    "genre": "Action",
    "hot": 413946,
    "summary": "Cowboy Bebop: The Movie收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-5.jpg"
  },
  {
    "id": "anime-38475",
    "title": "Laid-Back Camp: The Movie",
    "originalTitle": "映画 ゆるキャン△",
    "kind": "动漫电影",
    "year": 2022,
    "score": "8.4",
    "genre": "Slice of Life",
    "hot": 95473,
    "summary": "Laid-Back Camp: The Movie收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-38475.jpg"
  },
  {
    "id": "anime-9617",
    "title": "K-ON! The Movie",
    "originalTitle": "映画 けいおん！",
    "kind": "动漫电影",
    "year": 2011,
    "score": "8.4",
    "genre": "Award Winning",
    "hot": 357617,
    "summary": "K-ON! The Movie收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-9617.jpg"
  },
  {
    "id": "anime-5205",
    "title": "The Garden of Sinners Chapter 7: A Study in Murder - Part 2",
    "originalTitle": "劇場版 空の境界 the Garden of sinners 第七章『殺人考察（後）』",
    "kind": "动漫电影",
    "year": 2009,
    "score": "8.4",
    "genre": "Action",
    "hot": 220178,
    "summary": "The Garden of Sinners Chapter 7: A Study in Murder - Part 2收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-5205.jpg"
  },
  {
    "id": "anime-9260",
    "title": "Kizumonogatari Part 1: Iron-Blooded",
    "originalTitle": "傷物語〈Ⅰ鉄血篇〉",
    "kind": "动漫电影",
    "year": 2016,
    "score": "8.4",
    "genre": "Action",
    "hot": 584722,
    "summary": "Kizumonogatari Part 1: Iron-Blooded收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-9260.jpg"
  },
  {
    "id": "anime-48561",
    "title": "Jujutsu Kaisen 0",
    "originalTitle": "劇場版 呪術廻戦 0",
    "kind": "动漫电影",
    "year": 2021,
    "score": "8.4",
    "genre": "Action",
    "hot": 1286491,
    "summary": "Jujutsu Kaisen 0收录真实动漫电影海报、评分、年份、题材和观影指南，适合日本动漫电影在线观看与推荐。",
    "poster": "./posters/anime-48561.jpg"
  }
];
